export const DEFAULT_MILESTONES = [
  {
    name: "NTP / 开工令下达",
    description: "完成口径：EPC 开工令签发，总控计划、施工组织设计、HSE 方案批准。",
    isHardGate: false,
    sortOrder: 1,
  },
  {
    name: "施工前手续闭环",
    description: "完成口径：保安規程、主任技術者、必要时的工事計画相关手续完成；若建築確認适用，取得確認済証；消防协商/届出完成。日本建筑制度原则上要求工前确认、工后完了检査。",
    isHardGate: true,
    sortOrder: 2,
  },
  {
    name: "场地移交 / 临建完成",
    description: "完成口径：三通一平、围挡、临电、临水、测量放线完成，施工面正式移交。",
    isHardGate: false,
    sortOrder: 3,
  },
  {
    name: "土建开工",
    description: "完成口径：场平、地基处理、基础、排水、电缆沟正式开工。",
    isHardGate: false,
    sortOrder: 4,
  },
  {
    name: "主要基础完工",
    description: "完成口径：电池舱、PCS、升压变、配电/控制室基础验收通过，可转设备安装。",
    isHardGate: false,
    sortOrder: 5,
  },
  {
    name: "长周期设备 FAT 完成",
    description: "完成口径：电池舱、PCS、变压器、EMS/SCADA、保护计量等出厂测试闭环，具备发货条件。",
    isHardGate: false,
    sortOrder: 6,
  },
  {
    name: "主要设备到货完成",
    description: "完成口径：关键设备全部到场并完成到货验收、开箱检查、缺件闭环。",
    isHardGate: false,
    sortOrder: 7,
  },
  {
    name: "机电安装完成 / MC",
    description: "完成口径：设备就位、母线/电缆敷设与接线完成，接地、通信、HVAC、消防、气体探测等安装完成，A 类缺陷清零。",
    isHardGate: true,
    sortOrder: 8,
  },
  {
    name: "站内受电完成",
    description: `完成口径：站用电或 access 设备可用，具备调试电源。OCCTO 的接续资料会把\u201caccess 设备运用开始希望日\u201d和\u201c试运连系开始日\u201d分开；对系統用蓄电池，还要同时校核放电侧和充电侧的接入条件。`,
    isHardGate: false,
    sortOrder: 9,
  },
  {
    name: "单体调试完成",
    description: "完成口径：绝缘、接地、保护定值、计量、通信、BMS/PCS/变压器、消防联动等逐项通过。",
    isHardGate: false,
    sortOrder: 10,
  },
  {
    name: "系统联调完成 / Ready for Energization",
    description: "完成口径：EMS–BMS–PCS–保护–计量–远方通信全链路联通。日本的使用前检验/确认方法里，对蓄电所明确包含远隔监视控制试验和充放电试验。",
    isHardGate: true,
    sortOrder: 11,
  },
  {
    name: "试运行并网开始",
    description: `完成口径：开始试运并与电网联动。OCCTO 文件把\u201c试运的连系开始日\u201d和\u201c营业运行开始日\u201d分开列示，并要求在试运连系开始前具备技术要件。`,
    isHardGate: true,
    sortOrder: 12,
  },
  {
    name: "法定使用前检查 / 确认完成",
    description: "完成口径：按项目适用性完成工事計画关联的法定检验/确认；若项目触发建築確認，还应完成完了检査并取得检査済証。工事計画届项目在全部工事完成后实施使用前自主检査。",
    isHardGate: false,
    sortOrder: 13,
  },
  {
    name: "性能试验通过 / PAC",
    description: "完成口径：按合同通过额定功率、持续时长、辅助用电、响应时间、RTE（若合同约定）、告警/停机逻辑等测试。",
    isHardGate: false,
    sortOrder: 14,
  },
  {
    name: "COD / 营业运行开始 + 运维移交",
    description: `完成口径：商业运行条件满足，项目从建设转入运维。OCCTO 资料将\u201c营业运行开始\u201d作为独立时间点管理。`,
    isHardGate: true,
    sortOrder: 15,
  },
];
